baseURL: "/"
title: Soutenance de mémoire
theme: "hugo-theme-revealjs"

params:
    reveal_theme: black
    revealjs:
        controls: true
        progress: true
        history: true
        center: true
        height: 800
        width: 1500

disableKinds:
    - "sitemap"

outputs:
    home:
        - "html"
